language: rust
dist: bionic
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_script:
  - '[ "$TRAVIS_RUST_VERSION" = stable ] && rustup component add rustfmt'
  - cargo install cargo-tarpaulin
  - cargo install cargo-update
  - cargo install-update --all
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo test --no-default-features
  - '[ "$TRAVIS_RUST_VERSION" = stable ] && cargo fmt -- --check'
after_success: |
  # This requires a -Z flag for Doctests, which is current unstable
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin -f --ignore-panics --ignore-tests --run-types Tests Doctests --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
