language: rust
dist: bionic
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script: |
  rustup component add rustfmt
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo fmt -- --check
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
