[package]
name = "dangerous"
version = "0.1.0"
authors = ["avitex <avitex@wfxlabs.com>"]
edition = "2018"
description = "Safely and explicitly handle user-generated data"
categories = ["no-std", "parsing"]
documentation = "https://docs.rs/dangerous"
homepage = "https://github.com/avitex/rust-dangerous"
repository = "https://github.com/avitex/rust-dangerous"
license = "MIT"
readme = "README.md"

[features]
default = ["full-context", "unicode"]
# If enabled, implements `std::error::Error` on errors.
std = []
# If enabled, improves unicode printing support.
unicode = ["unicode-width"]
# If enabled, implements error terminal printing support.
terminal = ["std", "termcolor"]
# If enabled, shows full context backtraces.
# This feature requires allocation.
full-context = []

[dependencies]
termcolor = { version = "~1", optional = true }
unicode-width = { version = "0.1", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "context"
harness = false

[[example]]
name = "streaming"
required-features = ["std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
