[package]
name = "dangerous"
version = "0.1.1"
authors = ["avitex <avitex@wfxlabs.com>"]
edition = "2018"
description = "Safely and explicitly parse untrusted / dangerous data"
categories = ["no-std", "parsing"]
documentation = "https://docs.rs/dangerous"
homepage = "https://github.com/avitex/rust-dangerous"
repository = "https://github.com/avitex/rust-dangerous"
license = "MIT"
readme = "README.md"

[features]
default = ["full-context", "unicode"]
# Enables `std::error::Error` implementation for errors.
std = []
# Enables allocation.
# This feature also enables the boxing of `Expected`'s
# internals, improving performance of successful parsing.
alloc = []
# Enables improved unicode printing support.
unicode = ["unicode-width"]
# Enables full context backtraces.
full-context = ["alloc"]

[dependencies]
unicode-width = { version = "0.1", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "reader"
harness = false

[[bench]]
name = "context"
harness = false

[[example]]
name = "streaming"
required-features = ["std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
